apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operator-ns-rolebinding
  namespace: velero
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: operator-ns-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: testuser
