---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 30m
  chart:
    spec:
      chart: velero
      version: ">=1.15.0"
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: velero
      interval: 12h
  values:
    snapshotsEnabled: false
    deployNodeAgent: true
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.11.1
        volumeMounts:
          mountPath: "/target"
          name: plugins
