apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: testuser-devtest
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: developers-read
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: testuser
