apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: app1
  namespace: app1
spec:
  releaseName: app1
  chart:
    spec:
      chart: backstage
      sourceRef:
        kind: HelmRepository
        name: app1
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    ingress:
      enabled: true
      className: nginx
