apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hspc-operator-system
resources:
  - hspc-operator-namespace.yaml
  - hspc-operator.yaml
  - hspc_v1.yaml
  - sc-sample.yaml
  - hitachi-secret.yaml
