---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tenant
  namespace: minio
spec:
  values:
    ingress:
      api:
        host: minio.justinql.ca
      console:
        host: minio-stg.justinql.ca
