apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: app1
  namespace: app1
spec:
  chart:
    spec:
      version: "=2.3.1"
  values:
    ingress:
      host: backstage.justinql.ca
