---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tenant
  namespace: minio
spec:
  interval: 30m
  chart:
    spec:
      chart: tenant
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: minio
      interval: 12h
  values:
      tenant:
        pools:
          - servers: 1
            name: pool-0
            volumesPerServer: 1
            storageClassName: longhorn
            size: 1Gi
      ingress:
        api:
          enabled: true
          ingressClassName: nginx
        console:
          enabled: true
          ingressClassName: nginx
