---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tenant
  namespace: minio
spec:
  interval: 30m
  chart:
    spec:
      chart: tenant
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: minio
      interval: 12h
  values:
      tenant:
        pools:
          - servers: 1
            name: pool-0
            volumesPerServer: 1
            storageClassName: longhorn
            size: 1Gi
        buckets:
          - name: my-minio-bucket
            objectLock: false        # optional
            region: us-east-1        # optional
      ingress:
        api:
          enabled: true
          ingressClassName: nginx
          annotations:
            nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        console:
          enabled: true
          ingressClassName: nginx
          annotations:
            nginx.ingress.kubernetes.io/backend-protocol: HTTPS
