apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: app1
  namespace: app1-stg
spec:
  chart:
    spec:
      version: ">=2.4.0"
  values:
    ingress:
      host: backstage-stg.justinql.ca
