apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      version: ">=2.4.0"
  values:
    ingress:
      host: backstage-stg.justinql.ca
