---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 30m
  chart:
    spec:
      chart: keycloak
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts 
        namespace: keycloak
      interval: 12h
  values:
    ingress:
      enabled: true
      hostname: keycloak.justinql.ca
      ingressClassName: nginx
    adminIngress:
      enabled: true
      hostname: keycload-admin.justinql.ca
      ingressClassName: nginx
    keycloakConfigCli:
      enabled: true
      configuration:
        master.json: |
          {
            "realm" : "master",
            "attributes": {
              "frontendUrl": "https://keycloak-admin.example.com"
             }
           }
