apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kyverno
resources:
  - disallow-latest-tag.yaml
  - disallow-privileged-containers.yaml
  - enforce-readonly-rootfs.yaml
  - require-signed-images.yaml
  - restrict-default-namespace.yaml
  - restrict-image-registries.yaml
  - restrict-sa-token-mounting.yaml

