apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/ingress-nginx
  - ../base/minio
  - ../base/velero
  - ../base/rbac
  - ../base/hitachi
  - ../base/kyverno
patches:
  - path: minio-tenant.yaml
    target:
      kind: HelmRelease
  - path: ingress-nginx.yaml
  - path: velero.yaml
  - path: hitachi-sc.yaml
  - path: hitachi-secret.yaml
