apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/ingress-nginx
  - ../base/minio
  - ../base/velero
patches:
  - path: minio-tenant.yaml
    target:
      kind: HelmRelease
  - path: ingress-nginx.yaml
  - path: velero.yaml
