apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/ingress-nginx
  - ../base/minio
patches:
  - path: minio-tenant.yaml
    target:
      kind: HelmRelease
      name: ingress-nginx
      namespace: ingress-nginx2
  - path: ingress-nginx.yaml
    target:
      kind: HelmRelease
      namespace: minio
      name: tenant
