apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tenant
  namespace: minio
spec:
  chart:
    values:
      ingress:
        api:
          host: minio-stg.justinql.ca 
        console:
          host: minio-console-stg.justinql.ca
