---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  values:
    configuration:
      backupStorageLocation:
        - name: minio
          provider: aws
          bucket: my-minio-bucket
          default: true
          config:
            region: us-east-1
            s3ForcePathStyle: true
            s3Url: https://minio.minio.svc:443
            publicUrl: https://minio-stg.justinql.ca:30138
            insecureSkipTLSVerify: true
    credentials:
      secretContents:
        cloud: |
          [default]
          aws_access_key_id=0zkIuiLtY8QSl4Fzv0vo
          aws_secret_access_key=HM5MiZ5WA0pucIhomNUSA3SaSCPzQmB6E7xV8BV7
